web:
  host: XXXFQDNXXX
  protocol: https

fast_server:
  enabled: true
  bind_address: 0.0.0.0
  port: 5010
  ssl_port: 5011

general:
  use_ip_pools: false

main_db:
  host: 127.0.0.1
  username: root
  password: XXXMYSQL_ROOT_PASSWORDXXX
  database: postal

message_db:
  host: 127.0.0.1
  username: root
  password: XXXMYSQL_ROOT_PASSWORDXXX
  prefix: postal_msg

rabbitmq:
  host: 127.0.0.1
  username: postal
  password: XXXMYSQL_ROOT_PASSWORDXXX
  vhost: /postal

smtp_server:
  port: XXXSMTP_PORTXXX

dns:
  mx_records:
    - XXXFQDNXXX
  smtp_server_hostname: XXXFQDNXXX
  spf_include: spf.XXXFQDNXXX
  return_path: rp.XXXFQDNXXX
  route_domain: routes.XXXFQDNXXX
  track_domain: track.XXXFQDNXXX

smtp:
  host: 127.0.0.1
  port: XXXSMTP_PORTXXX
  #username:XXXADMIN_USERNAMEXXX
  #password:XXXADMIN_PASSWORDXXX
  from_name: XXXADMIN_USERNAMEXXX
  from_address: XXXADMIN_EMAILXXX

rails:
  secret_key: c3ed0d4723a5d08f8cdb03571ddec8366da74db114f5419187343632e9c0c0110da177c0cf79e6605a4ccfff6f2d9e716d99b6525401ad9c181466b57a1901ffeacb023d05c9ce69838dd826f54e29c846e9e3231697c6749648a9c706df20b50bec1d7ef81b0dbd91410b314c44a4c0cf74741df2de9f5bb144026a6f99954c
